import type { Metadata } from "next";
import { Inter, Lato, Montserrat } from "next/font/google";
import "./globals.css";
import React from "react";
import Layout from "@/components/layouts/Layout";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["100", "300", "400", "700", "900"],
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Admin Sela ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${montserrat.variable} ${lato.variable} bg-[#F0F0F0]`}
      >
        <GoogleOAuthProvider clientId={"771963944350-kq86tumrbh49irvbpq3h15bdki0rm9qo.apps.googleusercontent.com"}>
          <Layout>
            <div>{children}</div>
          </Layout>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
