export const dummy = [
  {
    name: "Luxury Villa Ubud with Private Pool Luxury Villa Ubud with Private Pool Luxury Villa Ubud with Private Pool Luxury Villa Ubud with Private Pool Luxury Villa Ubud with Private Pool",
    price: 4000000000,
    availability: "Available",
    landSize: 300,
    buildSize: 300,
    status: "Approved",
    published: false,
  },
  {
    name: "Luxury Villa Ubud with Private Pool",
    price: 4000000000,
    availability: "Available",
    landSize: 300,
    buildSize: 300,
    status: "Approved",
    published: true,
  },
  {
    name: "Luxury Villa Ubud with Private Pool",
    price: 4000000000,
    availability: "Available",
    landSize: 300,
    buildSize: 300,
    status: "Approved",
    published: false,
  },
  {
    name: "Luxury Villa Ubud with Private Pool",
    price: 4000000000,
    availability: "Available",
    landSize: 300,
    buildSize: 300,
    status: "Approved",
    published: true,
  },
];
